version: '3'
services:
  bookstack:
    image: solidnerd/bookstack:0.25.2
    environment:
    - DB_HOST=172.17.0.1
    - DB_DATABASE=bookstack
    - DB_USERNAME=root
    - DB_PASSWORD=123
    volumes:
    - ./uploads:/var/www/bookstack/public/uploads
    - ./storage-uploads:/var/www/bookstack/public/storage
    ports:
    - "8080:80"
    container_name: bookstack-app
